### ISSUE TITLE
Support for custom resolution

### ISSUE THREAD

**Issue by cmalvi** [Lahvuun/sekirofpsunlock#1]
As title, i think could be great for device like Steam Deck and 21:9 monitors. Thanks for your work!

**Comment by Lahvuun** [comment]
Should be usable now. The new command is called `sekiro-set-resolution`. There are a few issues with setting the resolution, I explain everything in the upadted readme.

I only have a 16:9 monitor, but I tested with gamescope and it seems to be working.

**Comment by cmalvi** [comment]
Wow really thank you! I’ll test it on my steam deck this evening

**Comment by Lahvuun** [comment]
Sure. Let me know if you have any issues — patching the resolution is a bit complex. I tried my best to explain everything, but you never know how others will interpret your instructions.

If everything works properly, you should have something similar to the following:
![image](https://user-images.githubusercontent.com/6643565/175926672-ed345361-ff2d-40b1-a373-f21d9a4667b9.png)
Note the darkened corners, they're there because the UI is not designed with other aspect ratios in mind. There is a mod that fixes it for 21:9, but nothing for 16:10 I'm afraid. The UI files are in Scaleform, Flash (as in Adobe Flash, ew). I have no experience with it, so I can't fix the UI, unfortunately. Maybe someone will produce a mod for 16:10 in the future.

**Comment by cmalvi** [comment]
Ok, one last question: how did you managed to launch it from gamescope?

**Comment by Lahvuun** [comment]
You need to set the launch options in Steam: `gamescope -- %command%` is the general idea. The command I used to simulate the Steam Deck resolution is `gamescope -w 1280 -h 800 -W 1920 -H 1080 -r 75 -- %command%`

**Comment by cmalvi** [comment]
Nevermind, I saw now the updated readme.
Thanks again

**Comment by cmalvi** [comment]
Using gamescope on steam deck, regarding lunch command, is the same as steam desktop.
I wrote the message without paying attention but I meant “how to run the patch when starting the game from steam”. I try now :)

**Comment by cmalvi** [comment]
Sorry for another message, in the readme you write the resolution to set in this format “X X Y”, is correct or just a mistype?

**Comment by Lahvuun** [comment]
Don't worry about the messages.

It is correct, but it is `X X Y` only if you're running the game in full screen mode. If you're running windowed, it'd be `X Y Z`, where X is the display width, Y is the windowed game width and Z is the windowed game height. Anyway, for fullscreen Steam Deck you probably want `1280 1280 800`

**Comment by cmalvi** [comment]
Tried now setting launch command from steam in this way:

./wait-and-patch.sh ./sekiro-set-resolution 1280 1280 800 %command%

But it exit after click on play, both desktop and gamescope

**Comment by Lahvuun** [comment]
That's almost right. But you're missing an ampersand (`&`) before `%command%`. Try 
```
./wait-and-patch.sh ./sekiro-set-resolution 1280 800 800 & %command%
```
Replace the paths to `wait-and-patch.sh` and `sekiro-set-resolution` with absolute paths, of course.

**Comment by cmalvi** [comment]
ok now the game launch but the patch doesn't apply, strange

i'm start thinking that i'm writhe the path worngy:

i've saved the repo at "home/deck/Documents/sekirofpsunlock'
./Documents ecc is correct?

**Comment by Lahvuun** [comment]
Ah, no. `./` is relative to the current working directory, which is the directory the game is in. Try
```sh
/home/deck/Documents/sekirofpsunlock/wait-and-patch.sh /home/deck/Documents/sekirofpsunlock/sekiro-set-resolution 1280 800 800 & %command%
```

**Comment by cmalvi** [comment]
tried with no success, game start but patch doesn't apply

maybe an && could help between the two executable?

**Comment by Lahvuun** [comment]
Nope. 

Can you use the terminal on the Deck? Generally the way you'd do this would be
- Run `./wait-and-patch.sh ./sekiro-set-resolution 1280 800 800` in the terminal. Don't close it.
- Start the game in Steam.

**Comment by cmalvi** [comment]
yes sure, just need to do from desktop mode (iit's an arch with kde)

**Comment by cmalvi** [comment]
doesn't work

**Comment by cmalvi** [comment]
it's a library problem, missing "/usr/lib/libc.so.6" version'GLIBC_2.34 not found

**Comment by Lahvuun** [comment]
Good catch! That's odd, though. Did you run `make` on a different machine and then transfer the files to Steam Deck?

**Comment by cmalvi** [comment]
yes, because i don't have a spare keyboard so i've used my main pc and then copy to steam deck with ssh.
In the steam deck there is 2.33 installed and from pacman 2.34 isn't avaiable

**Comment by cmalvi** [comment]
only for aarch64 and riscv64 there is

**Comment by Lahvuun** [comment]
Makes sense. I had the feeling this might happen, so I provided a release that is statically linked: https://github.com/Lahvuun/sekirofpsunlock/releases/tag/v0.1.0. Download the file called [x86_64.tar.gz](https://github.com/Lahvuun/sekirofpsunlock/releases/download/v0.1.0/x86_64.tar.gz) and unpack, it has the binaries that should work on the deck.

**Comment by cmalvi** [comment]
ok i'll try now

**Comment by cmalvi** [comment]
still not work, also tried from terminal and give the usage message

**Comment by Lahvuun** [comment]
Well, the only reason it can give that message is if you're not passing the correct number of arguments to the patcher. So, either, you're *not* running `./wait-and-patch.sh ./sekiro-set-resolution 1280 800 800`, or the `wait-and-patch.sh` finds `sekiro.exe` incorrectly.

Could you run `./wait-and-patch.sh echo`, start the game and then see what you get in the terminal? It should just be a single number, but you may be getting something else.

**Comment by cmalvi** [comment]
no output

**Comment by cmalvi** [comment]
i've also tested it on my pc using wait for patch and fps unlock, not working

**Comment by Lahvuun** [comment]
Can you verify that the FPS unlock works on your PC, then? Simply start the game, switch to the terminal and run:
```sh
./sekiro-set-fps $(pidof sekiro.exe) 120
```

**Comment by cmalvi** [comment]
doesn't work, it show the usage

![image](https://user-images.githubusercontent.com/76235393/175950544-f35fe77c-d922-4b5a-9577-a6765add3cc9.png)

**Comment by cmalvi** [comment]
tried also to run pidof sekiro.exe but exit with error, so i think this is the problem

**Comment by Lahvuun** [comment]
Right, now we're getting somewhere, This means that `pidof` fails to find `sekiro.exe`. Could you paste the output of
```ps -u $(whoami)```
while the game is running?
Make sure there is no personal information of yours (though it should just be process names)

**Comment by cmalvi** [comment]
38334 ?        00:07:47 sekiro.exe

you just need sekiro information right?

**Comment by Lahvuun** [comment]
> you just need sekiro information right?

Yup. Basically, the problem is that `pidof` doesn't find the process for some reason. I'm suspecting that Arch might have some weird version of `pidof` or, maybe, some security settings.

Anyway, test with `./sekiro-set-fps <pid> 144`, but replace `<pid>` with sekiro.exe pid you get from `ps -u $(whoami)`. *Hopefully* that will work fine, and then we can figure out why `pidof` doesn't work. And since Steam Deck is Arch, it probably has the same issue.

**Comment by cmalvi** [comment]
Using pid number works as expected, so the basic problem is pidof doesn't work as expected. Strange because i've used your mod in the past on the same installation on my pc

**Comment by Lahvuun** [comment]
And what about `pgrep`? Does `pgrep sekiro.exe` find the pid?

**Comment by cmalvi** [comment]
works

**Comment by Lahvuun** [comment]
Should be an easy fix, then. Just use `pgrep` instead of `pidof`!

You can simply update `wait-and-patch.sh` like so:
```sh
sed -i s/pidof/pgrep/ wait-and-patch.sh
```
Do it on the Deck and see if it works now.

**Comment by cmalvi** [comment]
#!/bin/sh
patcher="$1"

pid="$(pgrep sekiro.exe)"
pgrep_exit=$?
while [ $pgrep_exit -eq 1 ]
do
	pid="$(pgrep sekiro.exe)"
	pgrep_exit=$?
done

shift
"$patcher" $pid $@


is right?

**Comment by Lahvuun** [comment]
Yup, that's correct.

**Comment by cmalvi** [comment]
it works but not at launch (trying the fps on pc), i need to to it separately

**Comment by cmalvi** [comment]
here's the output of wait and patch

./wait-and-patch.sh: line 12: shift: shift count out of range
./wait-and-patch.sh: line 13: : command not found

**Comment by Lahvuun** [comment]
Can you paste the full command you're trying?

**Comment by cmalvi** [comment]
![image](https://user-images.githubusercontent.com/76235393/175956617-24d18d16-58dd-475b-bcc9-618f44d62a29.png)

**Comment by Lahvuun** [comment]
Oh, yeah, that makes sense. The script is meant to run another program once it finds the pid, so you can't just run it by itself. The usage would be as follows:
```sh
./wait-and-patch.sh <patcher> <patcher-arguments-except-pid>
```
So:
```sh
./wait-and-patch.sh ./sekiro-set-fps 144
```
and
```sh
./wait-and-patch.sh ./sekiro-set-resolution 1280 1280 800
```
Both:
```sh
./wait-and-patch.sh ./sekiro-set-resolution 1280 1280 800 && ./wait-and-patch.sh ./sekiro-set-fps 144
```
And, as a Steam launch option:
```
./wait-and-patch.sh ./sekiro-set-resolution 1280 1280 800 && ./wait-and-patch.sh ./sekiro-set-fps 144 & %command%
```
In the last example you'd have to set the paths to be absolute, of course, so:
```
/home/deck/Documents/sekirofpsunlock/wait-and-patch.sh /home/deck/Documents/sekirofpsunlock/sekiro-set-resolution 1280 1280 800 && /home/deck/Documents/sekirofpsunlock/wait-and-patch.sh /home/deck/Documents/sekirofpsunlock/sekiro-set-fps 144 & %command%
```

**Comment by cmalvi** [comment]
Stil not working (at startup i mean)

**Comment by Lahvuun** [comment]
Are you trying this on the deck, or on the PC? Also, if trying on the deck, did you set the correct paths (remember that the original binaries had the wrong libc version)

**Comment by cmalvi** [comment]
i'm trying on both, on the deck for 16:10 and on pc for 144 fps

The deck has the static linked version, the pc just cloned the repo because it has the right version of glibc
The path are correct (you helped me to fix)

Patch works, the problem seems the wait and patch part

**Comment by Lahvuun** [comment]
OK, so, there are two ways you can have it working on startup. The first is:
- Run `./wait-and-patch.sh ./sekiro-set-resolution 1280 1280 800 && ./wait-and-patch.sh ./sekiro-set-fps 144` (or similar) in the terminal. The command should just wait.
- Keep the terminal open.
- Run the game.
- Verify that the game has been patched.
- Once the game is patched, the terminal command should have finished.

The other way is having it in the Steam launch options. Which one doesn't work? Or is it both?

**Comment by cmalvi** [comment]
First, i can confirm the resolution patch works on the deck (not at startup), really thank you

The first method you suggested works (of course as previously tried), the problem is using as launch options (the only "usable" way for the steam deck)

Edit: i misunderstood your previosly suggestion
running the "first" suggestion lead to an error when the game start

find_pattern(pattern_framelock_fuzzy, ...) failed
patch_framelock() failed
patch() failed
set_fps() failed

**Comment by Lahvuun** [comment]
Alright, it's great to hear that the resolution patch works on the Deck!

I'm thinking that an easier, hands-off way is needed to run the patches with Steam. I'm going to have a good think about it, see if I can come up with a reliable and simple way to do it. I'll ping you once I have something ready. Thank you for all the troubleshooting!

**Comment by cmalvi** [comment]
> Alright, it's great to hear that the resolution patch works on the Deck!
> 
> I'm thinking that an easier, hands-off way is needed to run the patches with Steam. I'm going to have a good think about it, see if I can come up with a reliable and simple way to do it. I'll ping you once I have something ready. Thank you for all the troubleshooting!

Thanks to you really, i made and edit to my previous post

**Comment by Lahvuun** [comment]
I see it.

>`find_pattern(pattern_framelock_fuzzy, ...) failed`

That shouldn't be happening. This means that the patcher can't find the framelock in the game's code.

Try running the following commands while the game is running:
```sh
./wait-and-patch.sh ./sekiro-set-fps 144
```
and
```
./sekiro-set-fps $(pgrep sekiro.exe) 144
```
Do both of them fail with the same error? Also, are you running these on PC or on the Steam Deck?

**Comment by cmalvi** [comment]
both works in this way (same result on Pc and steam deck)

It works only when game already running

**Comment by Lahvuun** [comment]
So, 
```sh
./wait-and-patch.sh ./sekiro-set-fps 144
```
Gives you 
```
find_pattern(pattern_framelock_fuzzy, ...) failed
patch_framelock() failed
patch() failed
set_fps() failed
```
If you run it before the game?

**Comment by cmalvi** [comment]
yes, maybe after found the correct pid it needs to wait before patch?

**Comment by cmalvi** [comment]
Added sleep 20 before shift and did the trick, but still not work from launch argument

#!/bin/sh
patcher="$1"

pid="$(pgrep sekiro.exe)"
pgrep_exit=$?
while [ $pgrep_exit -eq 1 ]
do
	pid="$(pgrep sekiro.exe)"
	pgrep_exit=$?
done

sleep 20
shift
"$patcher" $pid $@

**Comment by Lahvuun** [comment]
Yeah, I'm thinking that this is because the game's code is encrypted. Looks like on your computer it doesn't decrypt fast enough. Could be something to do with the scheduling.

I didn't think this would be an issue, so I didn't bother adding a mechanism to wait until the decryption is finished. I'll need to think about how to add this, too.

I'll get back to you once (if) I can get this and the launch options working. I'm sure you're already getting tired from this tech support session, anyway.

**Comment by cmalvi** [comment]
ok, thanks again :) (not tired don't worry)

**Comment by Lahvuun** [comment]
@cmalvi 
Try [sekirofpsunlock.gz](https://github.com/Lahvuun/sekirofpsunlock/files/9023311/sekirofpsunlock.gz). It's a compressed executable (can't upload it here uncompressed), you can decompress with `gzip -d sekirofpsunlock.gz`, it'll produce the executable `sekirofpsunlock` in the same directory.

Run in the terminal:
```
./sekirofpsunlock 30 set-fps 144
```
And start the game.

There are a few changes:
- It'll look for the PID, no need to provide it.
- It'll wait until the `.data` section of the game starts changing. This might fix `find_pattern(pattern_framelock_fuzzy, ...) failed` for you.

The first option (30 in the example) is the timeout, in seconds. The program will bail if it can't find the process or `.data` doesn't change during this time.

Anyway, try it a few times, see if you run into any problems. Paste any error messages here. If you get the message `timeout reached while searching for sekiro.exe`, please paste the output of `/proc/$(pgrep sekiro.exe)/status`.

You can also use it to set the resolution and test it on the Steam Deck:
```
./sekirofpsunlock 30 set-resolution 1280 1280 800
```

**Comment by cmalvi** [comment]
Thanks for the update, I’ll try it tomorrow.

In the meantime, could you put this source in a different branch please? I’ve noticed some building problem with some other project on the steam deck due to missing dependencies or not available on their repos, so I think could be useful to test either the build process on it.

Also I think I didn’t fully understood the “.data” part, could you explain a little more please?

Thanks again :)

**Comment by Lahvuun** [comment]
>In the meantime, could you put this source in a different branch please?

Sure, I pushed the current code into the `rework` branch: https://github.com/Lahvuun/sekirofpsunlock/tree/rework. It's pretty messy, since I didn't intend for it to be released before you tested it, but it builds. There are no dependencies, so you should be able to build it on the Deck. Keep in mind I switched to the meson build system for a few reasons, so now the command to build it is `meson build -Dbuildtype=release && ninja -C build`. The binary (sekirofpsunlock) will be in the directory called `build`.

>Also I think I didn’t fully understood the “.data” part, could you explain a little more please?

Basically, binaries are made of different sections: normally `.text` is for code, `.rdata` for read-only data and `.data` is for modifiable data. `.data` has things like coordinates, item counts, etc. Things that change while the program is running. My theory is that during the decryption process, the protection does not touch `.data`. And only when it's done and actual code of the game starts being executed, then `.data` starts changing. So, if the program waits until that starts happening, it should be able to correctly apply all the patches.

The problem is that I'm not 100% sure `.data` doesn't change during the decryption process, and there's no way for me to test it reliably, so the person who can reproduce the problem, i.e. you, needs to do it.

**Comment by cmalvi** [comment]
Tried to build but failed with error (on pc):

Found ninja-1.11.0 at /usr/bin/ninja
ninja: Entering directory `build'
[1/3] Compiling C object sekirofpsunlock.p/src_fps.c.o
FAILED: sekirofpsunlock.p/src_fps.c.o 
cc -Isekirofpsunlock.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c17 -O3 -Wall -Wextra -Wpedantic -MD -MQ sekirofpsunlock.p/src_fps.c.o -MF sekirofpsunlock.p/src_fps.c.o.d -o sekirofpsunlock.p/src_fps.c.o -c ../src/fps.c
../src/fps.c:8:10: fatal error: common.h: No such file or directory
    8 | #include "common.h"
      |          ^~~~~~~~~~
compilation terminated.
[2/3] Compiling C object sekirofpsunlock.p/src_main.c.o
ninja: build stopped: subcommand failed.

**Comment by Lahvuun** [comment]
My bad, there were some old files. 91ed17a8fb17590eb18588c2eab80f206f51561d should fix that.

**Comment by cmalvi** [comment]
Tried with 30 timeout -- fail with the same error
Tried with 60 timeout -- success

Tried on pc, not on Steam Deck due to need of space for another game

**Comment by cmalvi** [comment]
Also retried as Steam launch command -- still not work even increasing further the timeout

**Comment by Lahvuun** [comment]
[sekirofpsunlock.gz](https://github.com/Lahvuun/sekirofpsunlock/files/9033744/sekirofpsunlock.gz)
Built from the latest rework commit: 6855e0d35f0ee403823f0dab0d01fd8fa0adaf9a
```
./sekirofpsunlock 30 set-fps 144
```
Should be working now.

**Comment by cmalvi** [comment]
Now 30 works, even as Steam launch command

Tested from pc

**Comment by cmalvi** [comment]
Maybe tomorrow I’ll download sekiro again on the Deck to test it from gamescope

**Comment by Lahvuun** [comment]
>Now 30 works, even as Steam launch command

That's great to hear!

**Comment by cmalvi** [comment]
Also, after I can confirm working flawless on the Deck from gamescope, I'll try to contact the modder about the ui

**Comment by Lahvuun** [comment]
> I'll try to contact the modder about the ui

Alright. If he agrees to do the 16:10 version, you can notify me so I can mention it in the readme.

I'm also merging `rework` into `master`.

**Comment by cmalvi** [comment]
Sure, the problem is there isn’t any direct contact method on the nexus mod page.
However I’ll notify you if I have any news about.

Thanks again :)

**Comment by cmalvi** [comment]
I forgot that I've had already wrote him in the post section.

I've seen now his reply

"I should be getting my Steam Deck in the next couple days so I will take look at modding the HUD for it then."

This is the page of the mod

https://www.nexusmods.com/sekiro/mods/240?tab=description

**Comment by Lahvuun** [comment]
Sweet! I'll keep an eye out for the 16:10 version.

**Comment by cmalvi** [comment]
Tested now on Steam Deck using Gamescope: runs perfectly as steam launch command using 30 delay

Thanks again :)
